# Prettier configuration
printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
jsxSingleQuote: true
trailingComma: 'es5'
bracketSpacing: true
bracketSameLine: false
arrowParens: 'always'
endOfLine: 'lf'
proseWrap: 'preserve'
htmlWhitespaceSensitivity: 'css'
quoteProps: 'as-needed'
plugins: ['prettier-plugin-tailwindcss']
tailwindConfig: './tailwind.config.ts' 